apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
- ../base
- secrets.yaml

images:
- name: 159049020511.dkr.ecr.us-east-1.amazonaws.com/kittykart-marketplace
  newTag: '0.0.1-alpha.4'

replicas:
- count: 1
  name: marketplace

configMapGenerator:
- behavior: merge
  literals:
  - LOG_LEVEL=debug
  - NODE_ENV=development
  name: marketplace-api-config

patchesJson6902:
- patch: |-
    - op: replace
      path: /metadata/name
      value: marketplace-dev-kittykart-io
    - op: replace
      path: /spec/secretName
      value: marketplace-dev-kittykart-io-tls
    - op: replace
      path: /spec/dnsNames/0
      value:  marketplace-dev.kittykart.io
  target:
    group: cert-manager.io
    kind: Certificate
    name: marketplace
    version: v1

# Don't need to edit the following ...
replacements:
- source:
    fieldPath: spec.secretName
    group: cert-manager.io
    kind: Certificate
    name: marketplace
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      group: networking.k8s.io
      kind: Ingress
      name: marketplace
      version: v1
- source:
    fieldPath: spec.dnsNames.0
    group: cert-manager.io
    kind: Certificate
    name: marketplace
    version: v1
  targets:
  - fieldPaths:
    - metadata.annotations.[external-dns.alpha.kubernetes.io/hostname]
    - spec.tls.0.hosts.0
    - spec.rules.0.host
    select:
      group: networking.k8s.io
      kind: Ingress
      name: marketplace
      version: v1
  - fieldPaths:
    - metadata.labels.[app.kubernetes.io/dnsname]
    - spec.template.metadata.labels.[app.kubernetes.io/dnsname]
    select:
      group: apps
      kind: Deployment
      name: marketplace
      version: v1
    options:
      create: true
- source:
    fieldPath: spec.template.spec.containers.[name=marketplace-api].image
    group: apps
    kind: Deployment
    name: marketplace
    version: v1
    options:
      delimiter: ':'
      index: 1
  targets:
  - fieldPaths:
    - metadata.labels.[app.kubernetes.io/version]
    - spec.template.metadata.labels.[app.kubernetes.io/version]
    select:
      group: apps
      kind: Deployment
      name: marketplace
      version: v1
    options:
      create: true
- source:
    fieldPath: metadata.namespace
    group: apps
    kind: Deployment
    name: marketplace
    version: v1
  targets:
  - fieldPaths:
    - metadata.labels.[app.kubernetes.io/environment]
    - spec.template.metadata.labels.[app.kubernetes.io/environment]
    select:
      group: apps
      kind: Deployment
      name: marketplace
      version: v1
    options:
      create: true