apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: marketplace
spec:
  secretName: marketplace-tls
  duration: 720h
  renewBefore: 168h
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: origin-issuer
  dnsNames:
  - fqdn
