apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/application: marketplace
    app.kubernetes.io/component: api
  name: marketplace
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/application: marketplace
        app.kubernetes.io/component: api
        app.kubernetes.io/environment: E
        app.kubernetes.io/version: V
    spec:
      serviceAccountName: marketplacesvc
      containers:
        - name: marketplace-api
          image: 159049020511.dkr.ecr.us-east-1.amazonaws.com/kittykart-marketplace
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: ENVIRONMENT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: APPLICATION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/application']
            - name: VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/version']
            - name: DNS_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/dnsname']
            - name: BASE_URL
              value: https://$(DNS_NAME)
          envFrom:
            - configMapRef:
                name: marketplace-api-config
            - secretRef:
                name: marketplace-api-secrets
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
